apiVersion: v1
kind: Pod
metadata:
  name: egress-1
  labels:
    name: egress-1
  annotations:
    pod.network.openshift.io/assign-macvlan: "true" 
spec:
  initContainers:
  - name: egress-1
    image: registry.redhat.io/openshift3/ose-egress-router
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    env:
    - name: EGRESS_SOURCE 
      value: 192.168.1.120
    - name: EGRESS_GATEWAY 
      value: 192.168.1.1
    - name: EGRESS_DESTINATION 
      value: 192.168.1.35
    - name: EGRESS_ROUTER_MODE 
      value: init
  containers:
  - name: egress-router-wait
    image: registry.redhat.io/openshift3/ose-pod
    imagePullPolicy: IfNotPresent
